data:
  root: dataset
  train_csv: train_5s_aug.csv
  val_csv: test_5s.csv
  test_csv: val_5s.csv
  sample_rate: 32000

training:
  epochs: 30
  batch_size: 32
  interval: 5

optimizer:
  pretrained_lr: 1e-4
  head_lr: 5e-3
  max_lr_pretrained: 5e-4
  max_lr_head: 8e-3
  weight_decay: 0.008

model:
  num_classes: 2
  model_type: wavegram_logmel
  unfreeze_last_layers: 3

weights:
  wavegram_logmel_weights: src/Wavegram_Logmel_Cnn14_mAP=0.439.pth
  resnet_weights: Placeholder.pth