$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json

name: pytorch-audio-env
description: Custom PyTorch audio env with PANNs & MLflow.

image: mcr.microsoft.com/azureml/curated/acpt-pytorch-2.2-cuda12.1:42

conda_file: ../environment.yml
