name: Start training job

on:
  pull_request:
    branches: [ main ]

jobs:
  train:
    if: contains(github.event.pull_request.labels.*.name, 'train')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -r requirements_ci.txt

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure ML CLI extension
        run: az extension add -n ml -y

      - name: Set Azure ML defaults
        run: |
          az configure --defaults \
            group=azuremlrg \
            workspace=azuremlws

      - name: Start training job
        run: |
          az ml job create -f scripts/train.yml

